### ISSUE TITLE
Miss typing suits

### ISSUE THREAD

**Issue by Moukou** [tsuntsuntsuntsun/Pokerbot#2]
![ss 2017-08-15 at 05 05 59](https://user-images.githubusercontent.com/31049191/29336576-40f56036-81dc-11e7-9a1e-ab0db7ca64ec.png)

It struggles with clubs and spades. A "flush" went past picking one club and four spades, here it shows two Kings both being spades which is of course impossible

![ss 2017-08-15 at 05 23 55](https://user-images.githubusercontent.com/31049191/29337285-c45c730e-81de-11e7-864a-2dcccd00afea.png)

Watching it a little more 5 and A are mixed up as well.

**Comment by tsuntsuntsuntsun** [comment]
Im looking into this, I will fix it in a few days. Thanks for pointing it out.
